CREATE TABLE "user_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(50) NOT NULL,
  "phone" varchar(30) NOT NULL,
  "password" varchar(50) NOT NULL,
  "join_date" DATE NOT NULL,
  "membership_t_idx" bigint NOT NULL
);

CREATE TABLE "membership_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "membership_name" varchar(50) NOT NULL,
  "description" text NOT NULL,
  "max_device" int NOT NULL
);

CREATE TABLE "profile_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "profile_name" varchar(50) NOT NULL,
  "profile_ico" varchar(100) NOT NULL,
  "game_nick" varchar(50),
  "is_kids_profile" bool DEFAULT false,
  "auto_play" bool DEFAULT true,
  "user_t_idx" bigint NOT NULL
);

CREATE TABLE "spectator_rating" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mode" int NOT NULL DEFAULT 0
);

CREATE TABLE "zzim_list_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "profile_t_idx" bigint NOT NULL,
  "content_t_idx" bigint NOT NULL
);

-- postgresql은 datetime 대신 timespamp 사용
CREATE TABLE "view_history_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "view_date" TIMESTAMP NOT NULL,
  "duration" int NOT NULL,
  "profile_t_idx" bigint NOT NULL,
  "movie_t_idx" bigint NOT NULL
);

CREATE TABLE "content_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "description" text NOT NULL,
  "thumbnail_path" varchar,
  "country" varchar(50) NOT NULL,
  "release_year" int NOT NULL,
  "add_date" date NOT NULL,
  "hit" bigint NOT NULL,
  "category_t_idx" bigint
);

CREATE TABLE "movie_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "thumbnail" varchar,
  "title" varchar,
  "movie_path" varchar,
  "desc" varchar,
  "content_t_idx" bigint
);

CREATE TABLE "content_genre_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_t_idx" bigint NOT NULL,
  "genre_t_idx" int NOT NULL
);

CREATE TABLE "genre_t" (
  "idx" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genre_name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "episode_t" (
  "idx" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "season" int NOT NULL,
  "title" varchar(50) NOT NULL,
  "description" text NOT NULL,
  "content_t_idx" bigint NOT NULL
);

CREATE TABLE "content_actor_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_t_idx" bigint NOT NULL,
  "actor_t_idx" bigint NOT NULL
);

CREATE TABLE "actor_t" (
  "idx" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "category_t" (
  "idx" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar(50) NOT NULL
);

ALTER TABLE "user_t" ADD FOREIGN KEY ("membership_t_idx") REFERENCES "membership_t" ("idx");

ALTER TABLE "profile_t" ADD FOREIGN KEY ("user_t_idx") REFERENCES "user_t" ("idx") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "view_history_t" ADD FOREIGN KEY ("profile_t_idx") REFERENCES "profile_t" ("idx") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "view_history_t" ADD FOREIGN KEY ("movie_t_idx") REFERENCES "movie_t" ("idx");

ALTER TABLE "content_genre_t" ADD FOREIGN KEY ("content_t_idx") REFERENCES "content_t" ("idx") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "content_genre_t" ADD FOREIGN KEY ("genre_t_idx") REFERENCES "genre_t" ("idx");

ALTER TABLE "content_actor_t" ADD FOREIGN KEY ("content_t_idx") REFERENCES "content_t" ("idx") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "content_actor_t" ADD FOREIGN KEY ("actor_t_idx") REFERENCES "actor_t" ("idx");

ALTER TABLE "movie_t" ADD FOREIGN KEY ("content_t_idx") REFERENCES "content_t" ("idx");

ALTER TABLE "content_t" ADD FOREIGN KEY ("category_t_idx") REFERENCES "category_t" ("idx");
