server:
  port: 82
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_dive
    username: starbox7
    password: starbox7
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
